---
logging:
  level:
    org:
      com: ~
      progex:
        hris: DEBUG
      springframework: ERROR
  pattern:
    console: "\"%d{yyyy-MM-dd HH:mm:ss} - %msg%n\""
    file: "\"%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n\""
server:
  port: "8080"
spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.H2Dialect
    show-sql: "true"
  main:
    banner-mode: "off"
